### ISSUE TITLE
[Error] Registering Class: java.lang.IllegalStateException: At path 'jdoStateManager'

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#258]
Hello, on the loading of the dev-server (I did not try on production environment) I get this error for each class I try to register.

I don't even know where to start the analysis because the stack is full related to Objectify

The last line of code of my class is this: 
it.noovle.ape.manager.ObjectifyManager.register(ObjectifyManager.java:88)
After that is all Objectify

Does anyone ever got this kind of error?

--------------------------------------------------------------------------
java.lang.IllegalStateException: At path 'jdoStateManager': Error registering it.noovle.ape.ds.object.APEObject
    at com.googlecode.objectify.impl.Path.throwIllegalState(Path.java:107)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:93)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
    at com.googlecode.objectify.impl.translate.CreateContext.getPopulator(CreateContext.java:41)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:76)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
    at com.googlecode.objectify.impl.translate.CreateContext.getPopulator(CreateContext.java:41)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:76)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
    at com.googlecode.objectify.impl.translate.CreateContext.getPopulator(CreateContext.java:41)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:76)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
    at com.googlecode.objectify.impl.translate.CreateContext.getPopulator(CreateContext.java:41)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:76)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.Translators.getRoot(Translators.java:129)
    at com.googlecode.objectify.impl.Registrar.register(Registrar.java:78)
    at com.googlecode.objectify.ObjectifyFactory.register(ObjectifyFactory.java:185)
    at it.noovle.ape.manager.ObjectifyManager.register(ObjectifyManager.java:88)
    at it.noovle.ape.manager.ObjectifyManager.register(ObjectifyManager.java:58)
    at it.noovle.ape.listener.ObjectifyServantLoader.contextInitialized(ObjectifyServantLoader.java:62)
    at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
    at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:266)
    at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:288)
    at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
    at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
    at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
    at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:258)
    at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
    at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:213)
    at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:211)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:211)
    at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:284)
    at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
    at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:226)
    at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:217)
Caused by: java.lang.NullPointerException
    at com.googlecode.objectify.impl.translate.CreateContext.getPopulator(CreateContext.java:38)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:76)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
    at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
    at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
    at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
    at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
    at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
    ... 69 more
--------------------------------------------------------------------------

**Comment by stickfigure** [comment]
Wow, that's pretty nutty. It looks like the JDO bytecode-created object is missing Object in its superclass hierarchy? I don't quite know how that is possible, but I checked in a fix to master.

**Comment by NicolaSpreafico** [comment]
After all this time I found the reason of the problem.
Using the Google Eclipse Plugin the DataNucleus enhancer was enabled by default (here is about the JDO things) and sometimes the "enhancement" fails creating a corrupted .class files
