### ISSUE TITLE
Objectify Filter error while using basic-scaling configuration on development environment

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#303]
Hello,
I have an App Engine maven project configured as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    <application>${app.id}</application>
    <version>${app.version}</version>
    <module>${module.name}</module>

    <sessions-enabled>true</sessions-enabled>
    <threadsafe>true</threadsafe>

	<instance-class>B1</instance-class>
	<basic-scaling>
	    <max-instances>2</max-instances>
	    <idle-timeout>10m</idle-timeout>
	</basic-scaling>

    <use-google-connector-j>true</use-google-connector-j>

    <system-properties>
    .....
```

With this objectify version
```
<dependency>
    <groupId>com.googlecode.objectify</groupId>
    <artifactId>objectify</artifactId>
    <version>5.1.13</version>
</dependency>
```

With this filter
```
<filter>
	<filter-name>ObjectifyFilter</filter-name>
       <filter-class>com.googlecode.objectify.ObjectifyFilter</filter-class>
</filter>
<filter-mapping>
       <filter-name>ObjectifyFilter</filter-name>
       <url-pattern>/*</url-pattern>
</filter-mapping>
```
Here is the log of the WTP server boot
```
lug 07, 2016 11:51:33 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFORMAZIONI: Overwriting system property key 'java.util.logging.config.file', value 'C:\Users\Nicola\.m2\repository\com\google\appengine\appengine-java-sdk\1.9.38\appengine-java-sdk\appengine-java-sdk-1.9.38\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'D:\Documenti\Java\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp10\autogrill-gpe\WEB-INF\appengine-web.xml'
lug 07, 2016 11:51:33 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
lug 07, 2016 11:51:38 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: jetty-6.1.x
lug 07, 2016 11:51:44 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: Started SelectChannelConnector@127.0.0.1:8888
lug 07, 2016 11:51:44 AM com.google.appengine.tools.development.JettyContainerService startHotDeployScanner
INFORMAZIONI: Full scan of the web app in place every 5s.
lug 07, 2016 11:51:44 AM com.google.appengine.tools.development.DevAppEngineWebAppContext disableTransportGuarantee
INFORMAZIONI: Ignoring <transport-guarantee> for /* as the SDK does not support HTTPS.  It will still be used when you upload your application.
lug 07, 2016 11:51:45 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: Module instance default is running at http://localhost:8888/
lug 07, 2016 11:51:45 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: The admin console is running at http://localhost:8888/_ah/admin
lug 07, 2016 11:51:49 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: jetty-6.1.x
lug 07, 2016 11:51:53 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: Started SelectChannelConnector@127.0.0.1:59716
lug 07, 2016 11:51:53 AM com.google.appengine.tools.development.JettyContainerService startHotDeployScanner
INFORMAZIONI: Full scan of the web app in place every 5s.
lug 07, 2016 11:51:53 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: Module instance default instance 0 is running at http://localhost:59716/
lug 07, 2016 11:51:53 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: The admin console is running at http://localhost:59716/_ah/admin
lug 07, 2016 11:51:54 AM com.google.appengine.tools.development.DevAppEngineWebAppContext disableTransportGuarantee
INFORMAZIONI: Ignoring <transport-guarantee> for /* as the SDK does not support HTTPS.  It will still be used when you upload your application.
lug 07, 2016 11:51:54 AM com.google.appengine.tools.development.LocalResourceFileServlet doGet
AVVERTENZA: No file found for: /_ah/start
lug 07, 2016 11:51:58 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: jetty-6.1.x
lug 07, 2016 11:52:01 AM com.google.apphosting.utils.jetty.JettyLogger info
INFORMAZIONI: Started SelectChannelConnector@127.0.0.1:59717
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.JettyContainerService startHotDeployScanner
INFORMAZIONI: Full scan of the web app in place every 5s.
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: Module instance default instance 1 is running at http://localhost:59717/
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.AbstractModule startup
INFORMAZIONI: The admin console is running at http://localhost:59717/_ah/admin
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.DevAppServerImpl doStart
INFORMAZIONI: Dev App Server is now running
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.DevAppEngineWebAppContext disableTransportGuarantee
INFORMAZIONI: Ignoring <transport-guarantee> for /* as the SDK does not support HTTPS.  It will still be used when you upload your application.
lug 07, 2016 11:52:01 AM com.google.appengine.tools.development.LocalResourceFileServlet doGet
AVVERTENZA: No file found for: /_ah/start
```
Once the development server is started, as soon I try to access to datastore I get the following error
```
it.noovle.ape.servlet.exception.FailedOperationException: java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.
	at it.noovle.ape.project.manager.JobLogManager.persist(JobLogManager.java:39)
	at it.noovle.ape.project.manager.JobLogManager.newPendingJob(JobLogManager.java:67)
	at it.noovle.ape.project.provisioning.Provisioner.newJob(Provisioner.java:76)
	at it.noovle.ape.project.provisioning.JobServlet.process(JobServlet.java:63)
	at it.noovle.ape.project.provisioning.AbstractServlet.process(AbstractServlet.java:90)
	at it.noovle.ape.project.provisioning.AbstractServlet.doPost(AbstractServlet.java:46)
	at it.noovle.ape.servlet.base.Base_Servlet.process(Base_Servlet.java:111)
	at it.noovle.ape.servlet.base.Base_Servlet.doPost(Base_Servlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at it.noovle.ape.filter.CustomWrapperFilter.doFilter(CustomWrapperFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirectedModuleRequest(DevAppServerModulesFilter.java:415)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at com.google.appengine.tools.development.JettyContainerService.forwardToServer(JettyContainerService.java:458)
	at com.google.appengine.tools.development.Modules.forwardToInstance(Modules.java:372)
	at com.google.appengine.tools.development.DelegatingModulesFilterHelper.forwardToInstance(DelegatingModulesFilterHelper.java:95)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirect(DevAppServerModulesFilter.java:326)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:119)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:511)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.
	at com.googlecode.objectify.ObjectifyService.ofy(ObjectifyService.java:44)
	at it.noovle.ape.project.manager.JobLogManager.persist(JobLogManager.java:37)
	... 49 more
```

I can confirm that the problem is the basic-scaling configuration because removing that part from the xml file the datastore works just fine w/o any problem.

The code this way is stuck attempting a write of an object
`ObjectifyService.ofy().save().entity(log).now()`

The strange thing, if I use the `59716` port instead of the `8888`, the first write is properly done.
After the write, a task is launched which will read the stored object. During the reading of the object the same error as above is thrown.

It is like, but I'm totally guessing here, basing of which instance is triggered (`8888` or `59716`) the objectify filter works or not

**Comment by stickfigure** [comment]
There's no ObjectifyFilter in that stacktrace. There's something wrong with your web.xml configuration; probably you have your CustomWrapperFilter set ahead of the ObjectifyFilter so it's not getting called. For further help, please use the Google Group (or stackoverflow if you prefer that venue). Thanks.

**Comment by NicolaSpreafico** [comment]
As already explained in the first message, I just need to remove the basic-scaling configuration and all the project works like a charm, so all the configuration (even my CustomWrapperFilter) works fine.

It cannot be a problem related to Objectify-Filter due to the project works fine simply changing the scaling configuration

**Comment by stickfigure** [comment]
This isn't an Objectify issue because there's no Objectify code being called (the stacktrace is clear). I don't know why changing the scaling configuration would have an effect on your servlet stack but maybe someone on the Google Group or Stackoverflow will have some insight? I'd start by posting your complete web.xml there. And triple-checking that you made no other changes in that deployment.

I hope you don't mind my closing this issue, you're just not likely to get an answer here. It's a GAE or Servlet question, not an Objectify question.

**Comment by NicolaSpreafico** [comment]
I already opened a ticket inside the Google Cloud support, but while I expecting reply from there I figured out to try even there to ask.
If you consider the problem not Objectify-related you can close this issue

Regards

**Comment by Judp0m** [comment]
NicolaSpreafico, I ran into the exact same issue. Did you figure out how to resolve this? I suppose Objectify needs to be initialized via the /_ah/start call. Objectify get initialized properly on GAE when using 	Automatic scaling, but not when using Manual scaling or Basic scaling...

**Comment by NicolaSpreafico** [comment]
@Judp0m, I quote the Google Support reply

> This is a known issue.
> It seems very easy on our side to reproduce this error and it appears to be a problem with the development server.
> I will reach out to the engineering team of the development server and try get some feedback on this issue.
> 
> I will let you know once I have an update, but I do not expect this to get resolved quickly.
> 
> However I understand that this problem only occurs in the local development server and only with the "max-instances" settings. 

The problem is shown only on development environment, there is no problem in the production environment. To make it work the local part, you need to comment out the part related to `scaling` configuration (the xml nodes), you can leave the instance class value enabled, due it does not have any effect on dev-server.

When you need to deploy, you can remove the comment from the `basic-scaling` configuration and you can deploy. Don't fear to forget to enable it, when you need to deploy leaving the instance-class disabled, the deploy ends with an error.

**Comment by boogie4eva** [comment]
Me and my team had the same issue and we have been trying to figure out why
it pops up on the local dev server .
Can't wait to see the resolution .

**Comment by gtgray** [comment]
I had the same issue and the following workaroung helped me: https://github.com/objectify/objectify/issues/307
