### ISSUE TITLE
Check for object loop while registering class

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#321]
Hi,
I have a structure like this:

```
    @Entity
    public class ObjectA {
        @Id
        private Long id;

        private ObjectB object;
    }

    @Entity
    public class ObjectB {
        @Id
        private Long id;

        private ObjectA object;
    }

    public static void main(String[] args) {
        ObjectifyService.register(ObjectA.class);
        ObjectifyService.register(ObjectB.class);
    }
```

During the register operation of those classes, I'm getting a recursive infinite loop
I did a little debug inside the library and I got the method which is called all the time

```
com.googlecode.objectify.impl.translate.Translators.get(TypeKey, CreateContext, Path)
```

The debug stack of Eclipse is like this
![image](https://cloud.githubusercontent.com/assets/12278553/23011822/4e1fbd0c-f423-11e6-8b46-3c52451362a3.png)

After some time the register operation ends with an Exception of `StackOverflowError` and I got this stacktrace

```
...
at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEmbeddedClassTranslator(ClassTranslatorFactory.java:75)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
....
```

Is there a way to prevent this kind of infinite loop?
Can I suggest some sort of consistency check during register operation which avoid to process already processed class?

**Comment by stickfigure** [comment]
This sort of recursive embedded structure has never been supported by Objectify. I will change this issue to an enhancement request.

**Comment by lostpebble** [comment]
I'd very much like this too. Just ran into this error today (which I've cut down significantly because it was long and recursive):

```
java.lang.StackOverflowError
	at java.lang.invoke.MemberName.isGetter(MemberName.java:630)
	at java.lang.invoke.MemberName.getMethodOrFieldType(MemberName.java:111)
	at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:71)
	at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:103)
	at java.lang.invoke.MethodHandles$Lookup.getDirectFieldCommon(MethodHandles.java:1700)
	at java.lang.invoke.MethodHandles$Lookup.getDirectFieldNoSecurityManager(MethodHandles.java:1691)
	at java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:1295)
	at java.lang.invoke.MethodHandles$Lookup.unreflectGetter(MethodHandles.java:1287)
	at com.googlecode.objectify.impl.FieldProperty.<init>(FieldProperty.java:41)
	at com.googlecode.objectify.impl.KeyMetadata.findKeyFields(KeyMetadata.java:77)
	at com.googlecode.objectify.impl.KeyMetadata.<init>(KeyMetadata.java:50)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:64)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory.create(EmbeddedMapTranslatorFactory.java:67)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory.create(EmbeddedMapTranslatorFactory.java:67)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.CreateContext.getTranslator(CreateContext.java:27)
	at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:88)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.createEntityClassTranslator(ClassTranslatorFactory.java:66)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:49)
	at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:36)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:138)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:117)
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory.create(EmbeddedMapTranslatorFactory.java:67)
```

I have a type of entity that acts like a node. It can be the parent or child of other entities of the same type. I want to keep an Embedded entity list on each entity which has the data for all of its parent entities. There will only ever be a maximum of 4 parents.

I know I can refactor it out into a different Entity. But I think this pattern could be quite useful for other things in the future - so checking for that recursion and preventing it could be quite useful.

The entity looks something like this (using Kotlin):

```
@Entity
class SimpleEntity {
    @Id var id: String? = null
    var parents: Map<String, SimpleEntityTest> = HashMap()
    @Index var parentIds: MutableList<String> = mutableListOf()
```

That recursive `Map` declaration is causing an error in `ObjectifyService.register()`

**Comment by stickfigure** [comment]
This feature would require some pretty extensive changes. The roadmap for Objectify is (currently) to keep it in maintenance mode until the REST APIs for the taskqueue and memcache mature, then do the major rewrite against the new APIs. Agreed that this would be a nice feature!

**Comment by lostpebble** [comment]
Okay, great. Roadmap sounds fair for the current changes coming.

Just realised that perhaps what I wanted was actually a bit of an anti-pattern, because it could cause some exploding and redundant data. I've just used inheritance instead- because the parents in that Map don't need to and shouldn't recursively hold maps of their parents too.

In the OP example, this feature request perhaps makes more sense.

**Comment by marooney01** [comment]
Hey there,
if it helps somehow, i just want to mention, that I've got the same issue **after** upgrading objectify 4 to 5.
This kind of recursive reference throws the same exception mentioned above, so i will stick to version  4.1.3 where this still works:


```
    @Entity
    public class ObjectA {
        @Id
        private Long id;
        private Key<ObjectA> object;
    }
```

**Comment by stickfigure** [comment]
@marooney01 there should not be any problem with a Key field. Are you sure you don't have an actual embedded structure?

**Comment by marooney01** [comment]
Ok thanks for the hint! It works now!
I do my own kind of lazy loading and have indeed a recursive object reference in there, which is not supposed to be touched by Objectify. The **IgnoreSave** Annotation seems to be handled differently in Objectify 5 now. I guess I should have used the **Ignore** annotation in first place anyway.
Here my test now:

Works with Objectify 4 but throws the translator exception in Objectify 5:
```
@Entity
public class TestEntity
{
     @Id private Long id;
     private Key<TestEntity> otherEntityKey;
     @IgnoreSave private TestEntity otherEntityObj;
}

```
Works with both 4 and 5:
```
@Entity
public class TestEntity
{
     @Id private Long id;
     private Key<TestEntity> otherEntityKey;
     @Ignore private TestEntity otherEntityObj;
}
```

Just continuing a hobby project after 4 years break. Upgrading to Objectify 5 is a great start already. You do an awesome job with this library! Thanks!

**Comment by kidogo** [comment]
Objectify is just perfect, great job Jeff and team. I have just stumbled on a need to embedding tree data structure like so:

```java
class Category{
   String name;
   List<Category> children;
}

@Entity
class Organization{
     List<Category> organzationCustomCategories;
}
```
With this:
- You avoid having to serialize and loose property visibility in datastore + property migration problems

- Avoid multiple datastore reads. You usually need all of these embedded objects together, and there may be tens or hundreds of them.

However, this causes StrackOverflowException because ```ClassTranslator<Category>``` needs ```ClassPopulator<Category>``` which in turn needs ```ClassTranslator<Category>``` for the children.

With somewhat evil modifications to ClassTranslator and ClassTranslatorFactory, it looks like someone may be able to achieve this by putting the the incompletely initialized ClassTranslator into the list of translators before initializing ClassPopulator. Below is a diff from 5.1.4:

```diff
diff --git a/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslator.java b/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslator.java
index a2b0ca2..eb8d48a 100644
--- a/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslator.java
+++ b/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslator.java
@@ -35,7 +35,7 @@
 	private final Creator<P> creator;
 
 	/** Does the heavy lifting of copying properties */
-	private final Populator<P> populator;
+	private Populator<P> populator;
 
 	/**
 	 * The discriminator for this subclass, or null for the base class.
@@ -92,6 +92,10 @@
 	public Populator<P> getPopulator() {
 		return populator;
 	}
+	
+	void setPopulator(Populator<P> populator) {
+		this.populator = populator;
+	}
 
 	/**
 	 * Get the creator associated with this class.
diff --git a/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslatorFactory.java b/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslatorFactory.java
index a7bc87a..efe9e3b 100644
--- a/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslatorFactory.java
+++ b/src/main/java/com/googlecode/objectify/impl/translate/ClassTranslatorFactory.java
@@ -70,11 +70,14 @@
 
 	/**
 	 */
-	public static <P> ClassTranslator<P> createEmbeddedClassTranslator(Class<P> clazz, CreateContext ctx, Path path) {
+	public ClassTranslator<P> createEmbeddedClassTranslator(Class<P> clazz, CreateContext ctx, Path path) {
 		Creator<P> creator = new EmbeddedCreator<>(clazz, ctx.getFactory());
-		Populator<P> populator = new ClassPopulator<>(clazz, ctx, path);
 
-		return new ClassTranslator<>(clazz, path, creator, populator);
+		ClassTranslator<P> result = new ClassTranslator<>(clazz, path, creator, null);
+		translators.put(clazz, result);
+		Populator<P> populator = new ClassPopulator<>(clazz, ctx, path);
+		result.setPopulator(populator);
+		return result;
 	}
 
 	/**

```

This seems not to have broken any tests. Any pointer to potential problems are highly appreciated.
