### ISSUE TITLE
Issue caused by failed memcache operations

### ISSUE THREAD

**Issue by nbali** [objectify/objectify#328]
First of all let's clarify that we have dedicated memcache with the following stats:
Dedicated (20 GB, 200k ops/sec)
Hit ratio | 91.21% | 3,417,497,685 hit / 329,223,846 miss
Items in cache | 15,315,614
Oldest item age | 3 days 13 hr
Total cache size | 19.27 GB

The issue we encountered is that the memcache contained an outdated state of the entity. To be precise it contains that it's missing, meanwhile it isn't. Compared to the whole amount of data the occurrence isn't high, but due it being critical business data it's effect is rather serious.

Anyway after some investigation we suspect it was caused by the lack of memcache update when the entity was first created.

```java
	at com.googlecode.objectify.cache.MemcacheServiceRetryProxy.invoke(MemcacheServiceRetryProxy.java:68)
	at com.sun.proxy.$Proxy10.putAll(Unknown Source)
	at com.googlecode.objectify.cache.KeyMemcacheService.putAll(KeyMemcacheService.java:91)
	at com.googlecode.objectify.cache.EntityMemcache.empty(EntityMemcache.java:312)
	at com.googlecode.objectify.cache.CachingAsyncDatastoreService$5.trigger(CachingAsyncDatastoreService.java:445)
	at com.googlecode.objectify.cache.TriggerFuture.isDone(TriggerFuture.java:87)
	at com.googlecode.objectify.cache.TriggerFuture.get(TriggerFuture.java:102)
	at com.googlecode.objectify.impl.ResultAdapter.now(ResultAdapter.java:34)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
	at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
	at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
```

I get that problems with handling memcache thrown exceptions. We can't retry it in ```MemcacheServiceRetryProxy``` till the end of time given that if the memcache is down it might never succeed (during that request I mean). Also throwing random exceptions out-of-the-blue might break application code.

My problem is that there is no way to get notified about any failed memcache operation. "Normal" memcache operations log it as SEVERE, retried operations as WARNING-WARNING-WARNING-SEVERE, but both eventually returns with null. For get* actions that might be fine, but for anything that updates the data is bad IMO.

- What I missing here, why would it be bad to use MemcacheServiceRetryProxy for every memcache operation?
- Why isn't there any exponential backoff between the retries?
- Would it be accepted if I would implement a new configuration possibility that would accept an object implementing an interface that would be called upon memcache failures? For example calling it with something (string/enum) that identifies operation we tried to do as one parameter, memcache namespace as another, and the list of keys that we couldn't clear for example as a third parameter, etc?
- Or do you see any better fix/workaround?

**Comment by nbali** [comment]
@stickfigure @ttozser @gabor-farkas fyi

**Comment by stickfigure** [comment]
Reads don't use the retry proxy because failure is not really a problem; we can just read through from the datastore instead. It doesn't make much sense to sit retrying the cache since it probably won't produce a different result and wastes time that could be better spent fetching the data from source.

Writes retry because failed writes a problem and can produce data inconsistency. How best to handle it is an open question. "try four times" was a totally arbitrary decision but makes sense; if you don't get a result in a couple tries you probably aren't going to get something different a few seconds later. Holding a connection blocked 10+ seconds will cause huge latency across the board if memcache goes away; you'll blow up your app and see a zillion instances start to handle the concurrent requests.

We could certainly add a hook that lets you handle this case arbitrarily... but I would be very very careful with what you intend to put there, especially if you have a lot of traffic. Exponential backoff schemes are a guaranteed disaster. Shunting the cache clear to a queue could work, but you have to be careful about overloading the queue add rate; you can literally take down your app with this.

**Comment by HansBrende** [comment]
@stickfigure overloading push queues can be avoided by using named tasks: adding a task to a queue will fail if there's already been a task with the same name. I'm with @nbali : if a memcache write fails after 4 tries and goes out of sync with the datastore, we need a hook allowing us to purge memcache as a last resort.

**Comment by stickfigure** [comment]
I've changed this to an enhancement request. It's not complex but it will have to come in the Objectify6 era.

**Comment by HansBrende** [comment]
@stickfigure also related is this [issue](https://github.com/objectify/objectify/issues/340) I opened recently. I think it makes sense to log critical errors that make memcache go out of sync with level `SEVERE`, as you do, but errors that don't make memcache go out of sync with only level `WARNING`. Making that distinction would be helpful in determining whether the error has caused memcache to go out of sync or not. When I get an e-mail associated with a `SEVERE` error, I'll know to manually purge memcache.

**Comment by nbali** [comment]
Btw maybe I don't remember well, but I think they have changed the thrown exception. If anyone have the original stack trace/remembers more accurately than I do, please feel free to correct me.

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.googlecode.objectify.cache.MemcacheServiceRetryProxy.invoke(MemcacheServiceRetryProxy.java:68)
	at com.sun.proxy.$Proxy34.putAll(Unknown Source)
	at com.googlecode.objectify.cache.KeyMemcacheService.putAll(KeyMemcacheService.java:91)
	at com.googlecode.objectify.cache.EntityMemcache.empty(EntityMemcache.java:323)
	at com.googlecode.objectify.cache.CachingTransaction$1.trigger(CachingTransaction.java:71)
	at com.googlecode.objectify.cache.TriggerFuture.isDone(TriggerFuture.java:87)
	at com.googlecode.objectify.cache.TriggerFuture.get(TriggerFuture.java:102)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
	at com.googlecode.objectify.util.FutureHelper.quietGet(FutureHelper.java:29)
	at com.googlecode.objectify.impl.TransactionImpl.commit(TransactionImpl.java:72)
	at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:123)
	at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:97)
	at com.googlecode.objectify.impl.TransactorNo.transact(TransactorNo.java:85)
	at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:192)
	at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:197)
Caused by: com.google.appengine.api.memcache.MemcacheServiceException: Memcache putAll: Unknown exception setting 1 keys
	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$RpcResponseHandler.handleApiProxyException(MemcacheServiceApiHelper.java:80)
	at com.google.appengine.api.memcache.AsyncMemcacheServiceImpl$RpcResponseHandlerForPut.handleApiProxyException(AsyncMemcacheServiceImpl.java:370)
	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$1.absorbParentException(MemcacheServiceApiHelper.java:129)
	at com.google.appengine.api.utils.FutureWrapper.handleParentException(FutureWrapper.java:56)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:95)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:28)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.putAll(MemcacheServiceImpl.java:117)
	... 66 more
Caused by: com.google.apphosting.api.ApiProxy$CapabilityDisabledException: The API call memcache.Set() is temporarily unavailable: 
	at com.google.apphosting.utils.runtime.ApiProxyUtils.getRpcError(ApiProxyUtils.java:142)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.setRpcError(ApiProxyImpl.java:619)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.failure(ApiProxyImpl.java:605)
	at com.google.apphosting.runtime.http.HttpApiHostClient.receivedResponse(HttpApiHostClient.java:266)
	at com.google.apphosting.runtime.http.JettyHttpApiHostClient$Listener.onComplete(JettyHttpApiHostClient.java:158)
	... 1 more 
```

Anyway my point being is that this ```CapabilityDisabledException``` is something that should be a clear candidate for this callback hook.
