### ISSUE TITLE
No class 'com.google.gson.internal.LinkedTreeMap' was registered

### ISSUE THREAD

**Issue by prasannaboppe** [objectify/objectify#339]
java.lang.IllegalArgumentException: No class 'com.google.gson.internal.LinkedTreeMap' was registered
	at com.googlecode.objectify.impl.Registrar.getMetadataSafe(Registrar.java:120)
	at com.googlecode.objectify.impl.Keys.getMetadataSafe(Keys.java:53)
	at com.googlecode.objectify.impl.Keys.getMetadataSafe(Keys.java:62)
	at com.googlecode.objectify.impl.Keys.requiresAutogeneratedId(Keys.java:121)
	at com.googlecode.objectify.impl.Deferrer.undefer(Deferrer.java:49)
	at com.googlecode.objectify.impl.WriteEngine.save(WriteEngine.java:73)
	at com.googlecode.objectify.impl.SaverImpl.entities(SaverImpl.java:60)

**Comment by stickfigure** [comment]
What version of Objectify is this? What does the entity you are saving look like?

**Comment by prasannaboppe** [comment]
I was trying to save an array of objects of type `CountryCode` contains three String variables like below.
`@Entity
public class CountryCode {
public String name;
@Id
public String alpha;
public String code;
}`

**Comment by stickfigure** [comment]
Objectify doesn't use GSON so that's coming from your codesomewhere. Where?

**Comment by prasannaboppe** [comment]
I'm using GSON to covert from json to object. I debugged it's working fine till the conversion part.

**Comment by prasannaboppe** [comment]
I think this issue is related to Configuration problem. Because the same code is working in my another project.

**Comment by stickfigure** [comment]
Perhaps try asking on the Objectify google group or stackoverflow? This is really a help request.
