### ISSUE TITLE
LoadException when doing projection query with list

### ISSUE THREAD

**Issue by gabriellet** [objectify/objectify#348]
Hello! 

I'm currently using objectify 5.1.12. When I try doing a projection query projecting a list, a LoadException is thrown. The GAE docs suggest that this [behavior is supported](https://cloud.google.com/appengine/docs/standard/java/datastore/projectionqueries#Java_Projections_and_multiple_valued_properties). I've included the stack trace. I believe #242 also has the same issue as me. Is this functionality something you would consider supporting? I've included the stack trace in case it is helpful to you.

Thanks!

```
com.googlecode.objectify.LoadException: Error loading !test:GroupReferral("c1b9ee9a-0ca0-4d9e-8caf-05e3aba6cd72:8dd19e32-fbba-46f0-b7ea-d289b9576e86"): com.google.appengine.api.datastore.RawValue cannot be cast to java.util.Collection

	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:78)
	at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:185)
	at com.googlecode.objectify.impl.ProjectionIterator.translate(ProjectionIterator.java:29)
	at com.googlecode.objectify.impl.ProjectionIterator.translate(ProjectionIterator.java:13)
	at com.googlecode.objectify.util.TranslatingIterator.next(TranslatingIterator.java:35)
	at com.google.common.collect.Iterators.addAll(Iterators.java:373)
	at com.google.common.collect.Lists.newArrayList(Lists.java:165)
	at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:22)
	at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:12)
	at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.util.ResultProxy.invoke(ResultProxy.java:34)
	at com.sun.proxy.$Proxy32.stream(Unknown Source)
	at [my function call here]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassCastException: com.google.appengine.api.datastore.RawValue cannot be cast to java.util.Collection
	at com.googlecode.objectify.impl.translate.CollectionTranslatorFactory$1.loadInto(CollectionTranslatorFactory.java:40)
	at com.googlecode.objectify.impl.translate.TranslatorRecycles.load(TranslatorRecycles.java:18)
	at com.googlecode.objectify.impl.PropertyPopulator.setValue(PropertyPopulator.java:100)
	at com.googlecode.objectify.impl.PropertyPopulator.load(PropertyPopulator.java:60)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:116)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:122)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:21)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:17)
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:74)
	... 40 more
```

**Comment by stickfigure** [comment]
Closing this because it is quite old. If it's still an issue, please post the structure of the entity class and we can reopen.
