### ISSUE TITLE
Enitities with annotation @AlsoLoad don`t saved to emulator with 6.0a1 version

### ISSUE THREAD

**Issue by muzuro** [objectify/objectify#350]
Thanks for great API!
Hi, i have wrote simple test:

```
package test;

import com.googlecode.objectify.ObjectifyService;
import com.googlecode.objectify.annotation.AlsoLoad;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import org.junit.Assert;
import org.junit.Test;
import static com.googlecode.objectify.ObjectifyService.ofy;

public class AlsoLoadTest {
    @Test
    public void testFilters() {
        ObjectifyService.register(Car.class);
        ObjectifyService.run(() -> {
            Car p = new Car("BMW", 250);
            ofy().save().entity(p).now();

            Car carByModel = ofy().load().type(Car.class).filter("model", p.getModel()).first().now();
            Car carByHorses = ofy().load().type(Car.class).filter("power >=", 1).first().now();
            System.out.println(carByModel);
            System.out.println(carByHorses);
            Assert.assertTrue(carByModel != null && carByHorses != null);
            return null;
        });
    }

    @Entity
    public static class Car {
        @Id
        private Long id;
        private String model;
        @AlsoLoad("horses")
        private int power;
        public Car(String model, int power) {
            this.model = model;
            this.power = power;
        }
    }
}
```
However i have exception when save is commited, here is stacktrace:
```
com.google.cloud.datastore.DatastoreException: 
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:129)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:155)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:418)
	at com.google.cloud.datastore.DatastoreImpl$5.call(DatastoreImpl.java:415)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:414)
	at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:408)
	at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:368)
	at com.googlecode.objectify.impl.AsyncDatastoreReaderWriterImpl.put(AsyncDatastoreReaderWriterImpl.java:55)
	at com.googlecode.objectify.impl.WriteEngine.save(WriteEngine.java:78)
	at com.googlecode.objectify.impl.SaverImpl.entities(SaverImpl.java:60)
	at com.googlecode.objectify.impl.SaverImpl.entity(SaverImpl.java:35)
	at com.qurasense.userApi.samples.objectify.AlsoLoadTest.lambda$testFilters$0(AlsoLoadTest.java:19)
	at com.googlecode.objectify.ObjectifyService.run(ObjectifyService.java:61)
	at com.qurasense.userApi.samples.objectify.AlsoLoadTest.testFilters(AlsoLoadTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.google.datastore.v1.client.DatastoreException: , code=UNKNOWN
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:226)
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:275)
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:186)
	at com.google.datastore.v1.client.Datastore.commit(Datastore.java:87)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:153)
	... 37 more
```
I am using  gradle dependency: `compile group: 'com.google.cloud', name: 'google-cloud-datastore', version: '1.14.0'`.

**Comment by stickfigure** [comment]
If I had to guess, there's something wrong with the way you are setting up the test harness. What datastore are you testing against? Also, that test doesn't actually test anything related to `@AlsoLoad` (if you want to test that feature, look at the AlsoLoadTests in the Objectify source, you have to construct the raw entity by hand). Also, you have the indexing issue :-)

**Comment by muzuro** [comment]
now can`t reproduce it, don`t know what it was
