### ISSUE TITLE
Objectify ShortBlob Load Exception

### ISSUE THREAD

**Issue by SetV** [objectify/objectify#351]
I am reading App Engine Datastore entry using `objectify` and got the following exception.

    com.google.api.server.spi.SystemService invokeServiceMethod:
        exception occurred while calling backend method (SystemService.java:375)
        com.googlecode.objectify.LoadException: Error loading UserData(5678701068944971):
        At path 'name': Expected class com.google.appengine.api.datastore.Blob,
        got class com.google.appengine.api.datastore.ShortBlob: <ShortBlob: 164 bytes>

From the GitHub issue [#284][1], this has been addressed in `5.1.11` release, however I am using `5.1.21` release and still getting the issue.

The Datastore entry is created through Cloud Datastore API, not through `objectify`. When the Datastore entry is created through `objectify` the error is not seen. Hope this helps to understand the issue.

[1]: https://github.com/objectify/objectify/issues/284

**Comment by stickfigure** [comment]
Can you post the full stacktrace, including the nested one?

**Comment by SetV** [comment]
Complete stacktrace is attached. I am not sure about the test case. I will go through and update.

    com.google.api.server.spi.SystemService invokeServiceMethod: exception occurred while calling backend method (SystemService.java:375)
    com.googlecode.objectify.LoadException: Error loading UserDate(5678701068944971): At path 'name': 
    Expected class com.google.appengine.api.datastore.Blob, got class 
    com.google.appengine.api.datastore.ShortBlob: <ShortBlob: 164 bytes>
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:78)
	at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:185)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:141)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:127)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:71)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.util.ResultNowFunction.apply(ResultNowFunction.java:20)
	at com.googlecode.objectify.util.ResultNowFunction.apply(ResultNowFunction.java:9)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.googlecode.objectify.impl.Chunk.next(Chunk.java:27)
	at com.googlecode.objectify.impl.Chunk.next(Chunk.java:10)
	at com.google.common.collect.Iterators$ConcatenatedIterator.next(Iterators.java:1425)
	at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1206)
	at com.googlecode.objectify.impl.ChunkingIterator.hasNext(ChunkingIterator.java:52)
	at com.yes.moviebox.spi.MovieDatabaseApi.queryMovies(MovieDatabaseApi.java:662)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:351)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:119)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:102)
	at com.google.api.server.spi.dispatcher.PathDispatcher.dispatch(PathDispatcher.java:50)
	at com.google.api.server.spi.EndpointsServlet.service(EndpointsServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.yes.moviebox.servlet.MemcacheFilter.doFilter(MemcacheFilter.java:94)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:297)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:202)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:108)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:642)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.IllegalStateException: At path 'name': Expected class 
    com.google.appengine.api.datastore.Blob, got class com.google.appengine.api.datastore.ShortBlob: 
    <ShortBlob: 164 bytes>
	at com.googlecode.objectify.impl.Path.throwIllegalState(Path.java:102)
	at com.googlecode.objectify.impl.translate.ValueTranslator.loadSafe2(ValueTranslator.java:29)
	at com.googlecode.objectify.impl.translate.ProjectionSafeTranslator.loadSafe(ProjectionSafeTranslator.java:36)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:17)
	at com.googlecode.objectify.impl.PropertyPopulator.setValue(PropertyPopulator.java:100)
	at com.googlecode.objectify.impl.PropertyPopulator.load(PropertyPopulator.java:60)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:116)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:122)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:21)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:17)
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:74)

**Comment by stickfigure** [comment]
This stacktrace appears to be coming from an old version of Objectify, before v5.1.11 . Is it possible that you have multiple versions on the classpath somehow?

**Comment by SetV** [comment]
I have deleted and deployed the Application again. I have verified `WEB-INF/lib` folder, only one version of Objectify is present v5.1.21.

The above call stack is from Google Cloud Platform Console Log. Is there an option to cross verify the Objectify version used in production server?

I am not using the App Engine Entity class to create the Datastore entry as mentioned in the test case. Following is the code snippet which will create the entry through Cloud Datastore API. I have cross verified the entry in Datastore.

    IncompleteKey key = datastore.newKeyFactory().setKind("UserData").newKey();
    FullEntity<IncompleteKey> entity = Entity.newBuilder(key)
		        .set("name", convertToBlobValue(user.getName()))
		        .build();

    static BlobValue convertToBlobValue(List<List<String>> list) throws IOException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(bos);
        oos.writeObject(list);
        return BlobValue.of(Blob.copyFrom(bos.toByteArray()));
    }

**Comment by stickfigure** [comment]
Can you show me what the POJO entity you are trying to load with Objectify looks like?

**Comment by SetV** [comment]
Following is the cut sort version of UserData class. I don't have issue when I the entry is create and read through the class as POJO entry.

The issue is seen when the entry is created through Cloud Datastore Client Library API. Hope you are aware.

    public class UserData {

        @Id
        private long id;

        @Index @Serialize
        private List<List<String>> name;

        @Index @Serialize
        private List<List<String>> surname;

        private List<String> address;
    }

**Comment by stickfigure** [comment]
AH!

`@Serialize` follows a different codepath than `byte[]`. This is a legitimate bug. I'll fix and release a new 5.x version today.

**Comment by stickfigure** [comment]
Fix released in v5.1.22.

**Comment by SetV** [comment]
Thanks for the update! It worked.
