### ISSUE TITLE
Strings not converted into Texts inside object lists

### ISSUE THREAD

**Issue by nbali** [objectify/objectify#360]
version: 5.1.21

```java
@Entity
public static class TestEntity {
	@Id
	private String id = "id";
	private String str;
	private List<Object> objects = Lists.newArrayList();
}
```
Failing code:
```java
		ObjectifyService.register(TestEntity.class);
		
		final TestEntity pojo = new TestEntity();
		pojo.str = Strings.repeat("a", 10); // works
		pojo.str = Strings.repeat("a", 1501); // works
		pojo.objects.add(Strings.repeat("a", 10)); // works
		pojo.objects.add(Strings.repeat("a", 1501)); // FAILS!
		
		ObjectifyService.ofy().save().toEntity(pojo);
```
Stacktrace:
```
com.googlecode.objectify.SaveException: Error saving TestEntity: objects: String properties must be 1500 bytes or less.  Instead, use com.google.appengine.api.datastore.Text, which can store strings of any length.
	at com.googlecode.objectify.impl.EntityMetadata.save(EntityMetadata.java:95)
	at com.googlecode.objectify.impl.SaverImpl.toEntity(SaverImpl.java:73)
Caused by: java.lang.IllegalArgumentException: objects: String properties must be 1500 bytes or less.  Instead, use com.google.appengine.api.datastore.Text, which can store strings of any length.
	at com.google.appengine.api.datastore.DataTypeUtils.checkSupportedSingleValue(DataTypeUtils.java:245)
	at com.google.appengine.api.datastore.DataTypeUtils.checkSupportedValue(DataTypeUtils.java:192)
	at com.google.appengine.api.datastore.DataTypeUtils.checkSupportedValue(DataTypeUtils.java:168)
	at com.google.appengine.api.datastore.DataTypeUtils.checkSupportedValue(DataTypeUtils.java:137)
	at com.google.appengine.api.datastore.PropertyContainer.setUnindexedProperty(PropertyContainer.java:119)
	at com.googlecode.objectify.util.DatastoreUtils.setContainerProperty(DatastoreUtils.java:161)
	at com.googlecode.objectify.impl.PropertyPopulator.save(PropertyPopulator.java:137)
	at com.googlecode.objectify.impl.translate.ClassPopulator.save(ClassPopulator.java:154)
	at com.googlecode.objectify.impl.translate.ClassTranslator.saveSafe(ClassTranslator.java:144)
	at com.googlecode.objectify.impl.translate.ClassTranslator.saveSafe(ClassTranslator.java:21)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.save(NullSafeTranslator.java:25)
	at com.googlecode.objectify.impl.EntityMetadata.save(EntityMetadata.java:89)
	... 4 more
```

If the ```objects``` would be ```List<String>``` it would work. My "guess" is that it checks the type of the field for the transformation, and not the type of the elements.

**Comment by stickfigure** [comment]
You are correct, this is expected behavior. The problem with declaring something Object is that Objectify can't really figure out what you want to do. Sure we could say converting String to Text makes sense on save, but do we convert Text to String on load?

If you declare Object as a type, you're effectively saying "I'll take care of any conversions" and Objectify just leaves it as-is. The same goes with `Key<?>`/`Key` conversions, `Integer`/`Long` conversions, array/`Set`/`List` conversions, etc.

**Comment by nbali** [comment]
Makes sense. Anyway did I miss the documentation about this? Or is this such an edge case that is why it wasn't included in https://github.com/objectify/objectify/wiki/Entities ?
