### ISSUE TITLE
404 Error running objectify on travis-ci

### ISSUE THREAD

**Issue by orinoco** [objectify/objectify#374]
I have a relatively straight forward cloud datastore app, deployed on appengine. I'm using Objectify 6. I am getting this error when running unit tests against the local datastore, on travis-ci.

> java.io.IOException: Error code 404 trying to get security access token from Compute Engine metadata for the default service account. This may be because the virtual machine instance does not have permission scopes specified.

A few notes:

- the test suite works fine on my local osx and windows machine
- it also works fine on a digital ocean ubuntu 16 instance
- storage and query ops works fine if I don't use Objectify (ie the equivalent traditional cloud datastore api)
- it's **not** working on a ubuntu 14 or 16 instance hosted by travis (on GCE, coincidentally)

I tried one little experiment, turned off my network locally and ran my test suites. Traditional GCP works fine, but Objectify produces a DatastoreException.

> com.google.cloud.datastore.DatastoreException: I/O error
> 	at com.rewattpower.dao.MeasurementTest.testObjectify(MeasurementTest.java:27)
> Caused by: com.google.datastore.v1.client.DatastoreException: I/O error
> 	at com.rewattpower.dao.MeasurementTest.testObjectify(MeasurementTest.java:27)
> Caused by: java.net.UnknownHostException: accounts.google.com
> 	at com.rewattpower.dao.MeasurementTest.testObjectify(MeasurementTest.java:27)
> 

So I suppose I'm wondering why Objectify needs to talk to google to run against the local datastore? Especially when appengine or cloud datastore ops don't?

Anyone have a simple objectify unit test running on travis?

**Comment by orinoco** [comment]
I eventually figured this out. Turns out, mvn was not getting the proper authentication, even though logged in with a service account. I was able to fix it by adding:

> export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json

where key.json is created in IAM -> Service Accounts ->App Engine default service account (ie. the same account being used to login with gcloud).
