### ISSUE TITLE
transaction crashed with java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V

### ISSUE THREAD

**Issue by niesteszeck** [objectify/objectify#376]
On Objectify 6, when starting a transaction it crashed with:

```
may 05, 2018 11:34:46 PM com.google.api.server.spi.SystemService invokeServiceMethod
GRAVE: exception occurred while calling backend method
java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V
	at com.google.datastore.v1.ArrayValue$Builder.addAllValues(ArrayValue.java:683)
	at com.google.cloud.datastore.ListValue$1.setValue(ListValue.java:66)
	at com.google.cloud.datastore.ListValue$1.setValue(ListValue.java:36)
	at com.google.cloud.datastore.Value$BaseMarshaller.toProto(Value.java:70)
	at com.google.cloud.datastore.Value.toPb(Value.java:217)
	at com.google.cloud.datastore.BaseEntity.toPb(BaseEntity.java:663)
	at com.google.cloud.datastore.BaseDatastoreBatchWriter.toMutationPbList(BaseDatastoreBatchWriter.java:266)
	at com.google.cloud.datastore.TransactionImpl.commit(TransactionImpl.java:103)
	at com.googlecode.objectify.impl.AsyncTransactionImpl.commit(AsyncTransactionImpl.java:87)
	at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:129)
	at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:93)
	at com.googlecode.objectify.impl.TransactorNo.transact(TransactorNo.java:81)
	at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:195)
	at cl.mydomain.myapp.api.ClientApi.saveClient(ClientApi.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:351)
```

ClientApi.java:39
```Client result = ofy().transact(() -> {```

**Comment by niesteszeck** [comment]
Finally I solved it adding dependency of protobuf on my pom.xml
```
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.5.1</version>
        </dependency>
```

**Comment by stickfigure** [comment]
Weird. This should be reported to Google here:

https://github.com/GoogleCloudPlatform/google-cloud-java

Objectify depends on that library, and it presumably is missing that dependency. Objectify doesn't do anything with protobufs.

That said, maybe it's something Google fixed already? If you declare a dependency on the most recent version of google-cloud-java, does it still happen?

**Comment by niesteszeck** [comment]
I'm struggling to get objectify 6 up and running, actually I started in a fresh branch. Now this error doesn't appear any more and I didn't have to add the mentioned dependency. Now I'm with problem mentioned on #361.

thx
