### ISSUE TITLE
Add support for java.time.LocalDateTime

### ISSUE THREAD

**Issue by DCFrancis** [objectify/objectify#377]
persist and read java.time.LocalDateTime (and related date concepts)
(and also sort, filter, etc...)

**Comment by EfraimLA** [comment]
How's going this issue? Any progress on this? I having an issue 

I'm getting this
`Caused by: java.lang.IllegalStateException: java.time.LocalDateTime must have a no-arg constructor
	at com.googlecode.objectify.impl.TypeUtils.getNoArgConstructor(TypeUtils.java:47)
	at com.googlecode.objectify.ObjectifyFactory.construct(ObjectifyFactory.java:161)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:111)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.PropertyPopulator.setValue(PropertyPopulator.java:95)
	at com.googlecode.objectify.impl.PropertyPopulator.load(PropertyPopulator.java:55)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:119)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:113)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:80)
	... 31 more
Caused by: java.lang.NoSuchMethodException: java.time.LocalDateTime.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at com.googlecode.objectify.impl.TypeUtils.getNoArgConstructor(TypeUtils.java:38)
	... 40 more`

**Comment by stickfigure** [comment]
Hmmm. We could store it as a String, but it's not really a native type of the datastore...

To get you up and running right away, make your own TranslatorFactory that handles LocalDateTime. You can pattern it after InstantTranslatorFactory. Register it with ObjectifyFactory.registrar.

**Comment by EfraimLA** [comment]
Thanks, i could configure Joda Time module but would be good have a native implementation.

@stickfigure Btw, there's a method like @Column(name="") or @Field(name="") for specifying the column names in datastore. I had a retries_clabe but when i saved changes to my entity changed all my underscored names to camelCase as written in Java. how could i do this ? I've searched in documentation and issues and didn't anything

Thanks :)
