### ISSUE TITLE
Cannot delete by array (varargs) of longs

### ISSUE THREAD

**Issue by michaeldimchuk** [objectify/objectify#414]
When trying to use `com.googlecode.objectify.impl.DeleteTypeImpl#ids(long[])`, an exception is thrown as the array of primitives is not correctly converted to a list of Long elements, so Objectify doesn't recognize it as a valid key type and throws an exception.

Sample code:
```
ofy().delete().type(AnyEntity.class).ids(1L, 2L, 3L).now();
```

Result was this stack trace:
```
java.lang.IllegalArgumentException: id '[J@53251a66' must be String or Long
	at com.googlecode.objectify.util.DatastoreUtils.createKey(DatastoreUtils.java:69)
	at com.googlecode.objectify.util.DatastoreUtils.createKeys(DatastoreUtils.java:115)
	at com.googlecode.objectify.impl.DeleteTypeImpl.ids(DeleteTypeImpl.java:91)
	at com.googlecode.objectify.impl.DeleteTypeImpl.ids(DeleteTypeImpl.java:75)
```

I found this was happening in my version of Objectify (5.1.22), as well as on master. For example I replaced the delete operation in `BasicTests#entitiesCanBeDeletedInBatch` with a `DeleteTypeImpl#ids(long[])` operation, and got a similar stack trace:
```
java.lang.IllegalArgumentException: id '[J@2b40ff9c' must be String or Long
	at com.googlecode.objectify.impl.Keys.createKeyAny(Keys.java:211)
	at com.googlecode.objectify.impl.Keys.lambda$createKeys$0(Keys.java:225)
        ...
	at com.googlecode.objectify.impl.Keys.createKeys(Keys.java:226)
	at com.googlecode.objectify.impl.DeleteTypeImpl.ids(DeleteTypeImpl.java:95)
	at com.googlecode.objectify.impl.DeleteTypeImpl.ids(DeleteTypeImpl.java:79)
```

The issue originates from `DeleteTypeImpl` and `DeferredDeleteTypeImpl` both using `java.util.Arrays#asList(T[])`. Because `long` is a primitive, `Arrays#asList` resolves `long[]` to be the type of `T`, not the individual `long` elements in the array, so the returned result is actually `List<long[]>` and is not a valid key from the perspective of Objectify.

**Comment by michaeldimchuk** [comment]
Pull request: https://github.com/objectify/objectify/pull/415
