### ISSUE TITLE
Objectify with PubSub

### ISSUE THREAD

**Issue by JulienSergent** [objectify/objectify#427]
I try to use objectify on pubsub messsage receive from pubsub.
I have an errors : Objectify context is not initialized (it's normal)
so i Use ObjectifyService.run( ... but when i try this  i have new error who say the environment is not define.

how to solve this ?

the java app run on GAE
objectify version : 5.1.8

thanks

**Comment by JulienSergent** [comment]
yes it's on GAE Standard this is my stacktrace : 

```
java.lang.NullPointerException: No API environment is registered for this thread.
	at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppId(DatastoreApiHelper.java:158)
	at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppIdNamespace(DatastoreApiHelper.java:175)
	at com.google.appengine.api.datastore.Key.<init>(Key.java:109)
	at com.google.appengine.api.datastore.Key.<init>(Key.java:97)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:83)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:76)
	at com.googlecode.objectify.util.DatastoreUtils.createKey(DatastoreUtils.java:84)
	at com.googlecode.objectify.util.DatastoreUtils.createKey(DatastoreUtils.java:74)
	at com.googlecode.objectify.impl.LoadTypeImpl.makeKey(LoadTypeImpl.java:144)
	at com.googlecode.objectify.impl.LoadTypeImpl.id(LoadTypeImpl.java:96)
	at com.kcloud.backend.lib.database.DAO.get(DAO.java:46)
	at com.kcloud.backend.business.account.service.AccountServiceImpl.getByEmail(AccountServiceImpl.java:74)
	at com.kcloud.backend.business.pack.business.PackBusinessImpl.receiveMessage(PackBusinessImpl.java:78)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:438)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```


this is my code : 

```
MessageQueueService.subscribeTopic(topics, subscription, this::receiveMessage);

private void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
  ObjectifyService.run(new VoidWork() {
    @Override
    public void vrun() {
      ofy().load()....
    }
  });
}
```

**Comment by JulienSergent** [comment]
sorry i don't t put he right stacktrace,

stacktrace with ObjectifyService.run :

```
java.lang.NullPointerException: No API environment is registered for this thread.
	at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppId(DatastoreApiHelper.java:158)
	at com.google.appengine.api.datastore.DatastoreApiHelper.getCurrentAppIdNamespace(DatastoreApiHelper.java:175)
	at com.google.appengine.api.datastore.Key.<init>(Key.java:109)
	at com.google.appengine.api.datastore.Key.<init>(Key.java:97)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:83)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:76)
	at com.googlecode.objectify.util.DatastoreUtils.createKey(DatastoreUtils.java:84)
	at com.googlecode.objectify.util.DatastoreUtils.createKey(DatastoreUtils.java:74)
	at com.googlecode.objectify.impl.LoadTypeImpl.makeKey(LoadTypeImpl.java:144)
	at com.googlecode.objectify.impl.LoadTypeImpl.id(LoadTypeImpl.java:96)
	at com.kcloud.backend.business.pack.business.PackBusinessImpl.lambda$receiveMessage$0(PackBusinessImpl.java:57)
	at com.googlecode.objectify.ObjectifyService.run(ObjectifyService.java:81)
	at com.kcloud.backend.business.pack.business.PackBusinessImpl.receiveMessage(PackBusinessImpl.java:57)
	at com.google.cloud.pubsub.v1.MessageDispatcher$4.run(MessageDispatcher.java:438)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stickfigure** [comment]
This is caused by not having the (legacy) GAE api installed. If you start a thread and want to use the old GAE services, you need to setup the (thread local) API environment. It's a bit out of my wheelhouse but this is probably a good place to start:

https://cloud.google.com/appengine/docs/standard/java-gen2/services/access
