### ISSUE TITLE
Db Save update failing

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#428]
The DB save which was working till today suddenly stops working in GAE. It shows below error/exception in logs.

com.we.wegaurd.datastore.DbService saveEntity: entity:save : (DbService.java:209)
com.google.apphosting.api.ApiProxy$UnknownException: An error occurred for the API request datastore_v3.Put().
	at com.google.apphosting.utils.runtime.ApiProxyUtils.statusException(ApiProxyUtils.java:209)
	at com.google.apphosting.utils.runtime.ApiProxyUtils.getRpcError(ApiProxyUtils.java:130)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.setRpcError(ApiProxyImpl.java:632)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.failure(ApiProxyImpl.java:618)
	at com.google.apphosting.runtime.http.HttpApiHostClient.communicationFailure(HttpApiHostClient.java:203)
	at com.google.apphosting.runtime.http.JettyHttpApiHostClient$Listener.onComplete(JettyHttpApiHostClient.java:167)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:735)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:271)
	at org.eclipse.jetty.client.PoolingHttpDestination.failed(PoolingHttpDestination.java:81)
	at org.eclipse.jetty.client.DuplexConnectionPool$1.failed(DuplexConnectionPool.java:159)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:84)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:588)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connectFailed(AbstractHttpClientTransport.java:152)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connect(AbstractHttpClientTransport.java:141)
	at org.eclipse.jetty.client.HttpClient$1.connect(HttpClient.java:593)
	at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:570)
	at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:563)
	at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:181)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68)
	at org.eclipse.jetty.io.ManagedSelector.size(ManagedSelector.java:104)
	at org.eclipse.jetty.io.SelectorManager.chooseSelector(SelectorManager.java:190)
	at org.eclipse.jetty.io.SelectorManager.connect(SelectorManager.java:207)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connect(AbstractHttpClientTransport.java:118)
	... 7 more
2019-09-03 21:43:56.034 IST
org.eclipse.jetty.client.TimeoutCompleteListener schedule: Scheduled timeout task org.eclipse.jetty.util.thread.ScheduledExecutorScheduler$ScheduledFutureTask@70c625aa in 62000 ms for HttpRequest[POST /rpc_http HTTP/1.1]@2d385755 (TimeoutCompleteListener.java:62)
2019-09-03 21:43:56.034 IST
org.eclipse.jetty.client.HttpDestination send: Queued HttpRequest[POST /rpc_http HTTP/1.1]@2d385755 for HttpDestination[http://169.254.169.253:10001]@3806c74b,queue=1,pool=DuplexConnectionPool[c=0/100,a=0,i=0] (HttpDestination.java:204)
2019-09-03 21:43:56.034 IST
org.eclipse.jetty.client.DuplexConnectionPool tryCreate: Connection 1/100 creation (DuplexConnectionPool.java:136)
2019-09-03 21:43:56.034 IST
org.eclipse.jetty.util.thread.QueuedThreadPool execute: queue org.eclipse.jetty.util.SocketAddressResolver$Async$$Lambda$22/1412787459@7cfadf3e (QueuedThreadPool.java:379)
2019-09-03 21:43:56.036 IST
com.we.wegaurd.manager.UserManager doUserLogin: com.we.wegaurd.manager.UserManagerdoUserLogin() :: exception :  (UserManager.java:1248)
com.google.apphosting.api.ApiProxy$UnknownException: An error occurred for the API request datastore_v3.RunQuery().
	at com.google.apphosting.utils.runtime.ApiProxyUtils.statusException(ApiProxyUtils.java:209)
	at com.google.apphosting.utils.runtime.ApiProxyUtils.getRpcError(ApiProxyUtils.java:130)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.setRpcError(ApiProxyImpl.java:632)
	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.failure(ApiProxyImpl.java:618)
	at com.google.apphosting.runtime.http.HttpApiHostClient.communicationFailure(HttpApiHostClient.java:203)
	at com.google.apphosting.runtime.http.JettyHttpApiHostClient$Listener.onComplete(JettyHttpApiHostClient.java:167)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:735)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:271)
	at org.eclipse.jetty.client.PoolingHttpDestination.failed(PoolingHttpDestination.java:81)
	at org.eclipse.jetty.client.DuplexConnectionPool$1.failed(DuplexConnectionPool.java:159)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:84)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:588)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connectFailed(AbstractHttpClientTransport.java:152)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connect(AbstractHttpClientTransport.java:141)
	at org.eclipse.jetty.client.HttpClient$1.connect(HttpClient.java:593)
	at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:570)
	at org.eclipse.jetty.client.HttpClient$1.succeeded(HttpClient.java:563)
	at org.eclipse.jetty.util.SocketAddressResolver$Async.lambda$resolve$1(SocketAddressResolver.java:181)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.keys(SelectorImpl.java:68)
	at org.eclipse.jetty.io.ManagedSelector.size(ManagedSelector.java:104)
	at org.eclipse.jetty.io.SelectorManager.chooseSelector(SelectorManager.java:190)
	at org.eclipse.jetty.io.SelectorManager.connect(SelectorManager.java:207)
	at org.eclipse.jetty.client.AbstractHttpClientTransport.connect(AbstractHttpClientTransport.java:118)

**Comment by stickfigure** [comment]
I don't know what's going on there, but there are no `com.googlecode.objectify` entries in that stacktrace. Whatever it is, it doesn't look like Objectify is involved.
