### ISSUE TITLE
Saving entity with Map field throws: DatastoreException: property.name contains a path delimiter and is indexed

### ISSUE THREAD

**Issue by asodja** [objectify/objectify#437]
We are moving from Objectify5 to Objectify6 (version 6.0.5) and we are getting exception for one of our entities:
```
com.google.cloud.datastore.DatastoreException: property.name contains a path delimiter, and the entity contains one or more indexed entity value.
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:154)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:492)
	at com.google.cloud.datastore.DatastoreImpl.commitMutation(DatastoreImpl.java:486)
	at com.google.cloud.datastore.DatastoreImpl.put(DatastoreImpl.java:446)
	at com.googlecode.objectify.impl.AsyncDatastoreReaderWriterImpl.put(AsyncDatastoreReaderWriterImpl.java:60)
	at com.googlecode.objectify.impl.WriteEngine.save(WriteEngine.java:78)
	at com.googlecode.objectify.impl.SaverImpl.entities(SaverImpl.java:60)
	at com.googlecode.objectify.impl.SaverImpl.entity(SaverImpl.java:35)
	at com.example.MapSave.saveWithObjectify(MapSave.java:53)
```

Reproducable case:
```
   public void saveJob() {
        try (Closeable closeable = OfySession.begin()) {
            saveWithObjectify();
        }
    }

    private void saveWithObjectify() {
        ObjectifyService.factory().register(Task.class);
        SimpleJob simpleJob = SimpleJob.builder()
                .value("123")
                .build();
        Task objectifyTask = Task.builder()
                .name("objectifyTask")
                .jobs(ImmutableMap.of("job.id", simpleJob))
                .build();
        ofy().save().entity(objectifyTask).now();
    }

    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @com.googlecode.objectify.annotation.Entity
    public static class Task {
        @Id
        private String name;
        private Map<String, SimpleJob> jobs;
    }

    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SimpleJob {
        private String value;
    }
```

It looks like, the problem is in "job.id". If we use "job-id" it works fine. Since this worked with Objectify5 we would like to avoid having some custom translator/stringifier for keys, since it can lead to funny bugs (e.g. if we replace all dots on save with '-' and then on load '-' with dots, we might replace some '-' that were not dots).

Since Objectify does not index by default my guess is that that kind of exception should not be thrown. 

Is there any workaround without key/value translation?

Note: It looks like this does not fail with Emulator datastore.

**Comment by asodja** [comment]
Just to add this, I tried it also with Native API and it looks like it works fine. Here is my code with Datastore native API that should be translated to the same entity:
```
    private void saveWithNativeAPI() {
        Datastore datastore = OfyService.factory().datastore();
        Key taskKey = datastore.newKeyFactory()
                .setKind("Task")
                .newKey("nativeTask");
        FullEntity<IncompleteKey> simpleJob = FullEntity.newBuilder()
                .set("value", "123")
                .build();
        EntityValue simpleJobValue = EntityValue.newBuilder(simpleJob)
                .setExcludeFromIndexes(true)
                .build();
        FullEntity<IncompleteKey> jobsEntity = FullEntity.newBuilder()
                .set("job.id", simpleJobValue)
                .build();
        EntityValue jobs = EntityValue.newBuilder(jobsEntity)
                .setExcludeFromIndexes(true)
                .build();
        Entity task = Entity.newBuilder(taskKey)
                .set("jobs", jobs)
                .build();
        datastore.put(task);
    }
```

**Comment by stickfigure** [comment]
Interesting, the surprise here is that the low level api seems to allow dots in keys _if it is unindexed_. I'll have to look into this.

**Comment by asodja** [comment]
Any news regarding this? 

I was checking code and it seems that one should apply this change in EmbeddedMapTranslatorFactory:
```
-                               return EntityValue.of(emb.build());
+                               return EntityValue.newBuilder(emb.build())
+                                               .setExcludeFromIndexes(index)
+                                               .build();
```
Although I am not familiar with code and I do not know how this would change behaviour. Especially since I saw some scary comment in ClassTranslator.java with similar code:
```
// The question of whether to index this is weird. In order for subthings to be indexed, the entity needs
// to be indexed. But then lists with index-heterogeous values (say, nulls) get reordered (!)
// by the datastore. So we always index EntityValues and force all the list translators homogenize their lists.
// Gross but seems to be the only way.
return EntityValue.of(into.build());
```

**Comment by stickfigure** [comment]
If we did this, then it becomes impossible to index anything nested inside. Ie in the original poster's test case, `@Index SimpleJob.value` would get ignored because the parent map container was excluded from indexes.

I'm not really sure what to do here. Google's low level library has a weird bit of behavior where dots are allowed in keys in certain cases but not others. Objectify doesn't really have enough knowledge to handle it (think about partial indexes with If conditions).

The only thing I can think of is that you just shouldn't allow dots in map keys... maybe use a lifecycle callback to translate them to something else. Or maybe get google to fix the low level library?
