### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/AsyncDatastoreService

### ISSUE THREAD

**Issue by fashAdmin** [objectify/objectify#438]
Hi stickfigure - would greatly appreciate your expert help and consideration:

I have run a Google App Engine project since 2015 using Objectify versions from 2.0 to 5.0 without any problems.  However with my last GAE project update on 11/24/19 the backend code will no longer startup due to the NoClassDefFoundError (stack trace below).

My project is a standard environment GAE app hosted on the Google Cloud Platform and uses Google Cloud Endpoints and Firebase APIs.  My IDE is Android Studio 2.3.3 using Gradle for dependencies and plugins.  I don't use Maven directly (therefore no pom.xml file).  I am using Objectify 5.1.17 (tried 5.1.22 but still same problem).

I have read and followed the Objectify Setup instructions at https://github.com/objectify/objectify/wiki/Setup and in the section 'Android Studio Setup 2.0' I see the dependency 'compile 'com.google.appengine:appengine-endpoints:1.9.28' //add this line to avoid upper comment' that is supposed to avoid the NoClassDefFoundError.

**However the build.gradle dependencies recommended in the setup instructions are deprecated as of 2017. They use dependencies based on an outdated Gradle plugin and no longer used with Google App Engine.  Please see links below for more info.**

https://github.com/GoogleCloudPlatform/gradle-appengine-plugin
https://github.com/GoogleCloudPlatform/app-gradle-plugin

Therefore I can't use the dependencies for Android Studio as listed on your Setup instructions.  I have spent hours trying to figure out solutions including using the dependencies recommended in the Setup instructions, manually compiling and uploading the com.google.appengine:appengine-java-sdk:1.9.28, creating a pom.xml file that doesn't use a provided scope, updating and trying different Gradle dependency permutations, removing project caches, etc. but nothing works.

I strongly suspect that recent code/API changes in Objectify or maybe the GAE platform have created a problem with using Objectify 5 because the exact same GAE code of my project that was uploaded and working fine on 11/10/19 no longer runs because of this Objectify error.

Thanks for any help and please ask for any additional info needed.

bK

Additional info:

**build.gradle file in my GAE project:**

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.0'
        classpath 'com.google.cloud.tools:appengine-gradle-plugin:1.3.2'
    }
}

repositories {
    jcenter();
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'com.google.cloud.tools.appengine'
apply plugin: 'com.google.cloud.tools.endpoints-framework-server'

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

dependencies {
    compile 'com.google.endpoints:endpoints-framework:2.0.7'
    compile 'com.google.http-client:google-http-client-gson:1.19.0' exclude module: 'httpclient'
    compile 'javax.inject:javax.inject:1'
    compile 'javax.servlet:servlet-api:2.5'
    compile 'com.googlecode.objectify:objectify:5.1.17'
    compile 'com.google.firebase:firebase-admin:4.1.1' exclude group: 'com.google.guava'
    compile 'com.google.guava:guava:20.0'
    compile group: 'com.google.appengine.tools', name: 'appengine-gcs-client', version: '0.7'
    compile "com.stripe:stripe-java:9.12.0"
}

This gradle.build file uses the updated GAE plugins recommended by Google since 2017.

**StackTrace:**

java.lang.NoClassDefFoundError: Could not initialize class com.googlecode.objectify.ObjectifyService
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:747)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:710)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:872)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)

**Another similar backend exception:**

2019-11-26 15:36:36.836 PST
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /_ah/warmup (JettyLogger.java:29)
java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/AsyncDatastoreService
	at com.googlecode.objectify.ObjectifyService.<clinit>(ObjectifyService.java:20)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:747)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:710)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:872)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.appengine.api.datastore.AsyncDatastoreService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at com.google.apphosting.runtime.ApplicationClassLoader.findClass(ApplicationClassLoader.java:135)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

**Comment by ludoch** [comment]
Can you try to add a dependency with
compile 'com.google.appengine.appengine-api-1.0-sdk:1.9.77'

Make sure this jar will be in your application path, as the server side does not provide it anymore.
Also, make sure you use the latest SDK tooling (GAE SDK or Cloud SDK) to do the deployment...

**Comment by fashAdmin** [comment]
Hi ludoch - 

Thanks for the advice but unfortunately adding the dependency to the build.gradle as you stated didn't work.

Although I didn't list this dependency explicitly in my old build.gradle, the appengine-api-1.0-sdk-1.9.77.jar was already being packaged in the WEB-INF/lib directory.  This jar was deployed to the Google Cloud Platform because I confirmed its presence by checking the uploaded library files in the Google Console.  Unfortunately the presence of the file didn't fix the NoClassDefFoundError.

Thanks again.

**Comment by ludoch** [comment]
Thanks!.
Next step, if you can would be to create a minimal project with objectify
and the SDK jar that can reproduce the issue in our side, this way, we
could debug it...
Ludo

**Comment by fashAdmin** [comment]
Thanks for the kind offer ludoch.

I will work on creating such a minimal project (stripped down version of my current project) over the next few days and upload to my Github profile. Then I'll comment again on this message chain.

However I also took your advice and carefully scrutinized my current GAE project and underlying GAE SDK software.  It's possible I am using the standalone App Engine SDK that was deprecated in July 2019 and thus won't load the proper GAE jars and dependencies.  I'll have to migrate to the new Cloud SDK which requires Gradle scripts for deployment.  Also looks like Android Studio no longer supports proper deployment of an App Engine project - need to use Gradle:

https://cloud.google.com/appengine/docs/standard/java/sdk-gcloud-migration
https://cloud.google.com/appengine/docs/standard/java/tools/migrate-gradle

I've been too dependent on Android Studio doing everything for me over the last 4 years (after migrating from Eclipse).  Strange how Google creates Android Studio but doesn't fully equip with the tools for backend project deployment like they used to.

Have a great Thanksgiving (if you're in the U.S.).

**Comment by fashAdmin** [comment]
Success!

Hi ludoch - I greatly appreciate your help.  You pointed me in the right direction and essentially your initial reply was correct.

In the end there was absolutely no problem with the Objectify platform but rather a glitch in the Google app engine deployment sdk.

Hopefully a summary of the solution will help others who may encounter this obscure error in the future:
- For some strange reason the GAE deployment dropped the upload of the com.google.appengine.appengine-api-1.0-sdk:1.9.77 jar even though it was clearly in my local build directory.
- This jar kept being shown in my local project _exploded-***App-AppEngine/WEB-INF/lib directory_.
- The solution was to:
1. Invalidate the project caches and restart/rebuild -> this removed the phantom appengine-api jar from the local build file that wasn't even being deployed.
2. Add the dependency you recommended to my build.gradle file as _compile group: 'com.google.appengine', name: 'appengine-api-1.0-sdk', version: '1.9.77'_
3. **Manually copy and past this jar file into the local WEB-INF/lib directory before deploying the project to the server.**  I got this last bit of advice from the following discussion: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2976

- For some reason the sdk jar still doesn't appear in the deployed lib directory when checking with the Google console.  Also the app.yaml file states _api_version: 'user defined'_

Nonetheless my deployed API classes are now recognized, no more NoClassDefFoundError, and my server API is working fine.  And I didn't need to use the Google Cloud sdk and pure Gradle console scripts - although I feel my day of reckoning is on the horizon with this last point.

Thanks a million again for helping me and finding the solution!

**Comment by fashAdmin** [comment]
Thanks so much!  You helped me find the solution with your wise advice.

https://github.com/objectify/objectify/issues/438

 Take care.

bK

**Comment by Ki-csen** [comment]
Hi All,
I faced the same issue and my solution is: you should use the gradle appengineDeploy command instead of gcloud app deploy.

**Comment by Ki-csen** [comment]
Hi i have faced the same issue during appcfg to gcloud command line tool migration. Finally I "gradle appengineDeploy" works for me instead of "gcloud app deploy".
