### ISSUE TITLE
Issue with loading entity when migrating from v5 to v6

### ISSUE THREAD

**Issue by healthy-interac** [objectify/objectify#442]
Hi,
We're going to migrate our project form Objectify 5 to 6. All migration tasks are done by following v5->v6 migration guide,  including running local appengine devserver and unit tests based on JUnit 5.
When we try to run our application in the cloud though, there is an issue with loading one specific entity 'User':

User user = OfyService.ofy().load().type(User.class).filter("email",email.toLowerCase()).first().now();

which is failing with the following exception:

com.google.apphosting.runtime.jetty9.JettyLogger warn: /auth/user/role (JettyLogger.java:29)
com.googlecode.objectify.LoadException: Error loading Key{projectId=diabetes-companion-exp, namespace=, path=[PathElement{kind=User, id=5692462144159744, name=null}]}: java.lang.String cannot be cast to com.google.cloud.datastore.FullEntity
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:84)
	at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:196)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:154)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:140)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:66)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.HybridQueryResults.lambda$load$1(HybridQueryResults.java:88)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.next(Iterators.java:1364)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:636)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.googlecode.objectify.impl.HybridQueryResults.hasNext(HybridQueryResults.java:93)
	at com.googlecode.objectify.util.IteratorFirstResult.nowUncached(IteratorFirstResult.java:31)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.LoadResult.now(LoadResult.java:25)
	at com.healthyinteractions.user.UserRoleHandler.loadUserByEmail(UserRoleHandler.java:57)
	at com.healthyinteractions.user.UserRoleHandler.doGet(UserRoleHandler.java:35)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.healthyinteractions.filters.AuditLogFilter.doFilter(AuditLogFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:747)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:710)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:680)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:872)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.google.cloud.datastore.FullEntity
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:89)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.PropertyPopulator.setValue(PropertyPopulator.java:95)
	at com.googlecode.objectify.impl.PropertyPopulator.load(PropertyPopulator.java:55)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:119)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:109)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:80)
	... 55 more

Same code runs just fine on local devserver, 'User' entity is loaded successfully (but these are new entities created with Objectify 6).
Other entities (of different kinds) are also loaded successfully.

I tried to analyze the code in com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe method, yet it doesn't seem obvious why this method is failing...

Also, is there a way to enable tracing of Objectify infrastructure code when running on GAE in the cloud?

Your advise will be much appreciated, thanks!

**Comment by healthy-interac** [comment]
Here is a `User` entity:

@Entity
public class User implements Serializable {

	@Id private Long id;

	@Index private String email;

	private String firstName;

	private String lastName;
	
	@Index private String role;

	private String passwordHash;
	
	private String phone;
	
	private String bio;
	
	private BlobKey picture;
	
	@Index private String sessionId;
	
	private Long passwordChanged;
	
	private LinkedList<String> previousPasswords;
	
	private Boolean defaultPassword;
	
        @Load
	@Index private Ref<Organization> organization;
	
	@Index private Long created = DateTime.parse(DEFAULT_CREATED).getMillis();

	private String bodyWeightUnit = HealthTrackingCategory.BODY_WEIGHT.getUnitUS();
	
	private String bloodGlucoseUnit = HealthTrackingCategory.BLOOD_GLUCOSE.getUnitUS();
	
	private Long lastMealViewDateTime;

	private Long changePasswordRequestTime;

	@Index private String changePasswordToken;
	
	private Long firstLogin;
	
	private Long lastLogin;
	
	private Long previousLogin;

	private Long joinedForumOn;

	private int failedLoginAttempts;

	private Long lockoutDateTime;

	private boolean coachInvited = true;
	
         @Load
	@Index private Set<Ref<User>> mySupportTeam = new HashSet<>();
	
	@Load
	@Index private Set<Ref<User>> otherSupportTeams = new HashSet<>();
	
	@Index private AccountStatus accountStatus = AccountStatus.ACTIVE;
	
	@Index private Long accountStatusChangedOn;
}

**Comment by healthy-interac** [comment]
Offender is found: 
private BlobKey picture;
BlobKey is not supported by Cloud SDK and as a result bu Objectify 6 as well.
