### ISSUE TITLE
Issue with loading of polymorphic hierarchy entity when migrating from v5 to v6

### ISSUE THREAD

**Issue by healthy-interac** [objectify/objectify#445]
Hi,

We're migrating our application from v5 to v6, currently using the latest version of Objectify 6.0.5.
Loading of polymorphic objects is working fine in our current Objectify 5 based code.

With Objectify 6.0.5 we're getting a LoadException when trying to iterate over list of loaded entities which are part of a polymorphic hierarchy:

com.google.apphosting.runtime.jetty9.JettyLogger warn: /auth/login/educator (JettyLogger.java:29)
com.googlecode.objectify.LoadException: Error loading Key{projectId=diabetes-companion-exp, namespace=, path=[PathElement{kind=ForumAbstractItem, id=5695159920492544, name=null}, PathElement{kind=ForumAbstractItem, id=5649050225344512, name=null}]}: Loaded Entity has parent but com.healthyinteractions.forum.ForumAbstractItem has no @Parent
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:84)
	at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:196)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:154)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:140)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:66)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.HybridQueryResults.lambda$load$1(HybridQueryResults.java:88)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.next(Iterators.java:1364)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:636)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.googlecode.objectify.impl.HybridQueryResults.hasNext(HybridQueryResults.java:93)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:22)
	at com.googlecode.objectify.util.MakeListResult.translate(MakeListResult.java:12)
	at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.util.ResultProxy.invoke(ResultProxy.java:32)
	at com.sun.proxy.$Proxy24.iterator(Unknown Source)
	at com.healthyinteractions.forum.ForumWorker.getUpdatedTopicsCount(ForumWorker.java:66)
	at com.healthyinteractions.user.UserProfileResponse.of(UserProfileResponse.java:56)
	at com.healthyinteractions.auth.LoginCoachWorker.getLoginResponse(LoginCoachWorker.java:68)
	at com.healthyinteractions.auth.LoginHandler.doPost(LoginHandler.java:46)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.healthyinteractions.filters.AuditLogFilter.doAuditFiler(AuditLogFilter.java:61)
	at com.healthyinteractions.filters.AuditLogFilter.doFilter(AuditLogFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle(ParseBlobUploadHandler.java:119)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle(AppEngineWebAppContext.java:187)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:293)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at com.google.apphosting.runtime.jetty9.RpcConnection.handle(RpcConnection.java:213)
	at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest(RpcConnector.java:81)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:134)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:752)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:715)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:685)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:877)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:270)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Loaded Entity has parent but com.healthyinteractions.forum.ForumAbstractItem has no @Parent
	at com.googlecode.objectify.impl.KeyMetadata.setKey(KeyMetadata.java:161)
	at com.googlecode.objectify.impl.KeyMetadata.setKey(KeyMetadata.java:141)
	at com.googlecode.objectify.impl.KeyPopulator.load(KeyPopulator.java:24)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:119)
	at com.googlecode.objectify.impl.translate.ClassPopulator.load(ClassPopulator.java:114)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:109)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.translate.ClassTranslator.loadSafe(ClassTranslator.java:100)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.load(NullSafeTranslator.java:21)
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:80)
	... 63 more

Here is the code trying to load and iterate over ForumTopic entities:

public class ForumWorker {
...
  List<ForumTopic> topics = OfyService.ofy().load().type(ForumTopic.class).filter("active", true).filter("user", Key.create(User.class, user.getId())).list();

  for (ForumTopic topic : topics) { // <== at com.healthyinteractions.forum.ForumWorker.getUpdatedTopicsCount(ForumWorker.java:66)
   //do some work

  }
...
}

Here is the hierarchy of objects:

@Entity
public abstract class ForumAbstractItem {

  @Id private Long id;
  @Index private Long timestamp;
  @Index private String subject;
  @Index @Load private Ref<User> user;
  private String userNickname;
  @Index private boolean active = true;
}

@Subclass(index = true)
public final class Forum extends ForumAbstractItem {
  //doesn't have any members
}

@Subclass(index = true)
public final class ForumTopic extends ForumAbstractItem {

  @Parent private Ref<Forum> forum;
  @Index private TopicCategory category;
  @Load private Ref<Organization> organization;
  private Map<String, Long> userLastViewed = new HashMap<>();
  @Index private int tagCount;
}

**Comment by stickfigure** [comment]
As mentioned in the google group - move your @Parent field to the base class (`ForumAbstractItem`), and null it out in the subclasses that you want to be parent-less. Probably best to continue this discussion in the group.
