### ISSUE TITLE
Limit on maximum keys when in Transaction

### ISSUE THREAD

**Issue by ofersadgat** [objectify/objectify#448]
Hi, we just ran into an error whereby we were getting the error:

```
com.google.cloud.datastore.DatastoreException: cannot write more than 500 entities in a single call
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.commit(HttpDatastoreRpc.java:154)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:496)
	at com.google.cloud.datastore.DatastoreImpl$4.call(DatastoreImpl.java:493)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.datastore.DatastoreImpl.commit(DatastoreImpl.java:492)
	at com.google.cloud.datastore.TransactionImpl.commit(TransactionImpl.java:108)
	at com.googlecode.objectify.impl.AsyncTransactionImpl.commit(AsyncTransactionImpl.java:93)
	at com.googlecode.objectify.cache.CachingAsyncTransaction.commit(CachingAsyncTransaction.java:87)
	at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:141)
	at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:95)
	at com.googlecode.objectify.impl.ObjectifyImpl.transactNew(ObjectifyImpl.java:222)
```

This was weird because we've already upgraded to 6.0.6 which has the following commit (specifically the lines)

https://github.com/objectify/objectify/commit/38b160818d062d6b43ed14fc4b6f430c512ae9df#diff-14a6f4fe365dcc67f3a676d34154c8cbR40-R52

My guess as to the problem with the above commit is that the DatastoreReaderWriter that its calling is a TransactionImpl class which itself is aggregating the calls. This means that despite the fact that the calls are being batched at this level of abstraction, they get aggregated below which causes us to still hit this error.

The datastore API does seem to allow transactions accross requests, but you have to go through the Datastore class. It doesnt seem like the DataStore class has exposed this, but commit seems to illustrate that it is possible:

```
    this.validateActive();
    List<Mutation> mutationsPb = this.toMutationPbList();
    com.google.datastore.v1.CommitRequest.Builder requestPb = CommitRequest.newBuilder();
    requestPb.setMode(Mode.TRANSACTIONAL);
    requestPb.setTransaction(this.transactionId);
    requestPb.addAllMutations(mutationsPb);
    CommitResponse responsePb = this.datastore.commit(requestPb.build());
    this.deactivate();
    return new TransactionImpl.ResponseImpl(responsePb, this.toAddAutoId().size());
```

If we set the same transaction id, it should be in the same transaction, right?

At the very least, there should be some sort of warning that upgrading from Objectify5 to 6 will cause this issue (as the appengine API doesnt have this limitation (it does the same as above, i.e. multiple requests with the same transaction id)).

**Comment by stickfigure** [comment]
In general, Objectify doesn't try to hide the APIs it is built on. Sometimes we can improve on limitations (eg, partitioning and batching fetches for too many keys) but some limitations (like # of entities in a transaction) are just inherent to the platform. I don't think there's anything we can do about that limit.

Should we document it? I'm inclined to say no - for one thing, I don't really know what all those limits are. And even if I did, they change. I couldn't possibly keep up.

In the interest of clearing out old issues, I am going to close this as wontfix for now. It's not a hard no and if you want to keep the conversation going that's fine. I just don't know what to do about it now.
