### ISSUE TITLE
Key is too long 

### ISSUE THREAD

**Issue by rmaclean-ee** [objectify/objectify#469]
We are using Objecify with 6.0.7* and enabled the caching with Memcached and are getting the following error `java.lang.IllegalArgumentException: Key is too long (maxlen = 250)`

`Error obtaining cache for [Key{projectId=***, namespace=, path=[PathElement{kind=***, id=null, name=ce284a75-0b84-474a-8510-e80976719023}, PathElement{kind=***, id=null, name=4e28936a-ea14-4e3e-a2ac-fbfbc8338419}]}]`

```
java.lang.IllegalArgumentException: Key is too long (maxlen = 250)
Wrapped by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.googlecode.objectify.cache.MemcacheServiceRetryProxy.invoke(MemcacheServiceRetryProxy.java:54)
	at com.sun.proxy.$Proxy38.putAll(Unknown Source)
```

It is not consistent, some queries are working perfectly, and nothing is breaking - all the queries return etc... It is more annoying that our logs are spammed a lot and potentially some queries aren't getting the benefit of cache. 

Is there something we can configure or change?

* Not saying this is a regression, this has been this way since we turned on Memcached caching - just giving the version for details.

**Comment by stickfigure** [comment]
Well that's an interesting problem.  The google-cloud-datastore Key.toUrlSafe() produces an incredibly verbose string. Memcached has a limit of 250 chars. A couple path elements and long key names or long entity names and you can hit the limit. Oops.

There are a pair of private methods, KeyMemcacheService.fromCacheKey() and toCacheKey(). Right now they call Key.toUrlSafe() and Key.fromUrlSafe(). We could just make this configurable or we could simply change the implementation. I guess the risk of changing the implementation is that someone might already be relying on this behavior.

I guess we'll have to make this configurable.
