### ISSUE TITLE
InvocationTargetException is keep happening but no clue

### ISSUE THREAD

**Issue by amandeepfull** [objectify/objectify#472]
Objectify version: 5.1.21

logs:

```com.googlecode.objectify.cache.MemcacheServiceRetryProxy invoke: Error performing memcache operation, retrying: public abstract void com.google.appengine.api.memcache.MemcacheService.putAll(java.util.Map) (MemcacheServiceRetryProxy.java:73)
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.googlecode.objectify.cache.MemcacheServiceRetryProxy.invoke(MemcacheServiceRetryProxy.java:68)
	at com.sun.proxy.$Proxy18.putAll(Unknown Source)
	at com.googlecode.objectify.cache.KeyMemcacheService.putAll(KeyMemcacheService.java:91)
	at com.googlecode.objectify.cache.EntityMemcache.empty(EntityMemcache.java:323)
	at com.googlecode.objectify.cache.CachingTransaction$1.trigger(CachingTransaction.java:71)
	at com.googlecode.objectify.cache.TriggerFuture.isDone(TriggerFuture.java:87)
	at com.googlecode.objectify.cache.TriggerFuture.get(TriggerFuture.java:102)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:90)
	at com.googlecode.objectify.util.FutureHelper.quietGet(FutureHelper.java:29)
	at com.googlecode.objectify.impl.TransactionImpl.commit(TransactionImpl.java:72)
	at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:123)
	at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:97)
	at com.googlecode.objectify.impl.ObjectifyImpl.transactNew(ObjectifyImpl.java:219)
	at com.anywhereworks.commons.rtm.services.RTMUserPresenceService.updateUserPresence(RTMUserPresenceService.java:92)
```
	
Please let me know if you need anything else.

Thanks in advance!

**Comment by stickfigure** [comment]
InvocationTargetException is a wrapper exception. It's impossible to know what the issue is from here; you need the "Caused By" exception inside it.
