### ISSUE TITLE
Recurring NullPointerException where LoadEngine is null

### ISSUE THREAD

**Issue by daswass** [objectify/objectify#481]
This NPE seems to occur a few times per week, but never from user-initiated requests. The application is a web app using GCP and Endpoints and every request hits this code path to get the requesting user from the datastore. There is a service account that is hardcoded as a Ref and retrieved with a Ref#get if the server sees the request header from App Engine cron. Any ideas why this NPE hits sporadically?

```
java.lang.NullPointerException
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:66)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.LoaderImpl.now(LoaderImpl.java:269)
	at com.googlecode.objectify.impl.ref.LiveRef.get(LiveRef.java:47)
	at com.sserman.propertymanagement.business.authorization.DefaultAuthorizationService.getServiceAccount(DefaultAuthorizationService.java:71)
	at com.sserman.propertymanagement.business.authorization.DefaultAuthorizationService.getRequester(DefaultAuthorizationService.java:38)
	at com.sserman.propertymanagement.application.DatastoreNamespaceFilter.filter(DatastoreNamespaceFilter.java:81)
	at com.sserman.propertymanagement.application.DatastoreNamespaceFilter.doFilter(DatastoreNamespaceFilter.java:55)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
```

**Comment by tclass** [comment]
Hey, I have the exact error also only once in a while. I looked into it and can't find out why, does anyone have any pointers what could be the problem?

**Comment by stickfigure** [comment]
I'm *wildly* guessing this is some sort of scoping issue? If these requests aren't wrapped in the ObjectifyFilter, are you sure they're running from ObjectifyService.run() or following the ObjectifyService.begin().close() contract?

**Comment by nbartels** [comment]
I also run into this problem from time to time. The `ObjectifyFilter` is used and I was able to narrow down the error to `tranlated` to be null. I'll try to dig deeper, but maybe the info is already somehow useful for you guys ;)
