### ISSUE TITLE
Error Executing Native Image Using Index and Unindexes

### ISSUE THREAD

**Issue by EfraimLA** [objectify/objectify#497]
Hello i want some help because i'm getting an error when registering an Entity to ObjectifyService in Native Image (compiled) Quarkus Application

**Quarkus Version**
2.16.6.Final

**Java Version (GraalVM CE)**
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18, mixed mode, sharing)

**Maven Version**
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)

This is the error
```shell
2023-06-07 19:23:19,698 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.NoSuchMethodException: com.googlecode.objectify.condition.Always.<init>()
        at java.base@17.0.7/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.7/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2754)
        at com.googlecode.objectify.impl.TypeUtils.getNoArgConstructor(TypeUtils.java:38)
        at com.googlecode.objectify.ObjectifyFactory.construct(ObjectifyFactory.java:161)
        at com.googlecode.objectify.impl.IfConditionGenerator.createIf(IfConditionGenerator.java:65)
        at com.googlecode.objectify.impl.IfConditionGenerator.generateIfConditions(IfConditionGenerator.java:41)
        at com.googlecode.objectify.impl.FieldProperty.<init>(FieldProperty.java:61)
        at com.googlecode.objectify.impl.translate.ClassPopulator.getDeclaredProperties(ClassPopulator.java:212)
        at com.googlecode.objectify.impl.translate.ClassPopulator.<init>(ClassPopulator.java:87)
        at com.googlecode.objectify.impl.translate.ClassTranslator.<init>(ClassTranslator.java:76)
        at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:45)
        at com.googlecode.objectify.impl.translate.ClassTranslatorFactory.create(ClassTranslatorFactory.java:34)
        at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:147)
        at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:126)
        at com.googlecode.objectify.impl.translate.Translators.getRoot(Translators.java:138)
        at com.googlecode.objectify.impl.EntityMetadata.<init>(EntityMetadata.java:54)
        at com.googlecode.objectify.impl.Registrar.register(Registrar.java:65)
        at com.googlecode.objectify.ObjectifyFactory.register(ObjectifyFactory.java:241)
        at com.googlecode.objectify.ObjectifyService.register(ObjectifyService.java:44)
        at com.fonyou.citlal.config.UserSpaceLifeCycle.onStart(UserSpaceLifeCycle.java:33)
        at com.fonyou.citlal.config.UserSpaceLifeCycle_Observer_onStart_caa4f5ab05a64d454119b2444824c45e6cc00f7a.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
``` 

This is my entity
```java
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@RegisterForReflection
@Entity(name = "animation-progress")
@Index
public class ContractProgress {

    @Id
    private String id;

    private String animation_name;

    private Instant animation_date;

    @Unindex
    private String animation_data;

    private Boolean animation_finished;

}
```

**Comment by ygyg70** [comment]
I added to reflect-config.json the following Objectify classes:
            Always.class,
            IfDefault.class,
            IfEmpty.class,
            IfEmptyString.class,
            IfFalse.class,
            IfNotDefault.class,
            IfNotEmpty.class,
            IfNotNull.class,
            IfNotZero.class,
            IfNull.class,
            IfTrue.class,
            IfZero.class,
            PojoIf.class,
            ValueIf.class
            NullStringifier.class,
            KeyStringifier.class,
            EnumStringifier.class,

Also made some other changes to the code - you can find them here https://github.com/ygyg70/objectify

**Comment by EfraimLA** [comment]
Thanks, i need a fast solution because i'm implementing this thing in a project will launch next week so i don't have time to make the fix and publish my own library, just adding those classes to reflect-config would work? Or do i need the fix in FieldProperty class? Thanks u very much

**Comment by EfraimLA** [comment]
Actually it worked, i just put the FieldProperty in the same package inside my project (replacing it) and added the changes you made, also i created the reflection-config json with those classes and worked. I'll be using this trick while waiting the patched version of the library. Thanks, again!

and well, there is no way to avoid adding those classes to the reflection config explicitly ?

**Comment by ygyg70** [comment]
As far as I understand, a reflection config file can be added to the library and it will be picked up when building the image
