### ISSUE TITLE
Using `!=`, `in` or `not in` with datastore emulator leads to Exception

### ISSUE THREAD

**Issue by nbartels** [objectify/objectify#498]
According to the [docs](https://cloud.google.com/datastore/docs/tools/datastore-emulator?hl=en) and my tests, the emulator does not support `!=`, `in` and `not in` in filters. Using these filters results in an exception. 

It would be great, if objectify can hide the exception and replace the datastore filtering with a plain java version in case of the emulator is used.

```
com.google.datastore.v1.client.DatastoreException: , code=UNKNOWN
     at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:171)
     at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:239)
     at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:100)
     at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119)
     at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:200)
     at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:237)
     at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:1)
     at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
     at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
     at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
     at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:233)
     at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:93)
     at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:76)
     at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:206)
     at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:186)
     at com.googlecode.objectify.impl.AsyncDatastoreReaderWriterImpl.run(AsyncDatastoreReaderWriterImpl.java:60)
     at com.googlecode.objectify.cache.CachingAsyncDatastoreReaderWriter.run(CachingAsyncDatastoreReaderWriter.java:59)
     at com.googlecode.objectify.impl.QueryEngine.queryNormal(QueryEngine.java:58)
     at com.googlecode.objectify.impl.QueryImpl.iterator(QueryImpl.java:324)
     at com.googlecode.objectify.impl.QueryImpl.list(QueryImpl.java:332)
```

**Comment by stickfigure** [comment]
It's not really practical for me to reimplement emulator behavior - I'm afraid this is something that google will to have to fix.
