### ISSUE TITLE
Error after migrating from v5 to V6

### ISSUE THREAD

**Issue by cojalvo** [objectify/objectify#503]
Hi, I'm trying to upgrade from V5 to V6, and I'm getting the following error:

```
com.googlecode.objectify.LoadException: Error loading Key{projectId=******, namespace=, path=[PathElement{kind=Track, id=********, name=null}]}: Expected type ENTITY at path 'start' but instead found LAT_LNG
```

I have an entity that holds an embedded class from type LatLng and now after the migration I'm getting this error.
I am not sure how to handle it, any help will be appreciated.

**Comment by cojalvo** [comment]
@stickfigure Thanks for responding... I will post more info:
So it's happening in all Entities I'm using the GeoPt class as an embedded class, for example:
```
@Entity
@Cache
public class Navigation {
    @Id
    Long id;
    @Parent
    Ref<MyAdventureUser> userRef;
    Ref<Track> trackRef;
    @Index
    Date start;
    Date end;
    Ref<TripGroup> tripGroupRef;
    GeoPt startPoint;
    GeoPt endPoint;
....
}
```

Here is the full stack trace:
```

com.googlecode.objectify.LoadException: Error loading Key{projectId=brilliant-will-93906, namespace=, path=[PathElement{kind=MyAdventureUser, id=4761047353786368, name=null}, PathElement{kind=Navigation, id=6375807089377280, name=null}]}: Expected type ENTITY at path 'startPoint' but instead found LAT_LNG
	at com.googlecode.objectify.impl.EntityMetadata.load(EntityMetadata.java:84)
	at com.googlecode.objectify.impl.LoadEngine.load(LoadEngine.java:196)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:154)
	at com.googlecode.objectify.impl.LoadEngine$1.nowUncached(LoadEngine.java:140)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:66)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.LoadResult.now(LoadResult.java:25)
	at com.example.cadan.myapplication.backend.api.MyAdventureEndpointV2.insertNavigationLayers(MyAdventureEndpointV2.java:2643)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:351)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:119)
	at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle(EndpointsMethodHandler.java:102)
	at com.google.api.server.spi.dispatcher.PathDispatcher.dispatch(PathDispatcher.java:50)
	at com.google.api.server.spi.EndpointsServlet.service(EndpointsServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:78)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java…[message truncated due to size]
```

Im quite stack as I cant deploy a new version of my server as I'm getting allot of errors like these...

**Comment by stickfigure** [comment]
Looks like you're trying to use the legacy google `GeoPt` class, which the new google library (and Objectify 6) doesn't know anything about. The new class is `LatLng`. Replace all the `GeoPt` references with `LatLng` in your code and you should be fine.

**Comment by cojalvo** [comment]
@stickfigure this one? `com.google.appengine.repackaged.com.google.type.LatLng`

**Comment by cojalvo** [comment]
Ok, im guessing its not the correct type as I'm getting this error:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.google.cloud.datastore.LatLng` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

**Comment by cojalvo** [comment]
@stickfigure  any idea? I also tried to create my own LatLng class and use it but I got a lot of errors saying it’s not the expected type. I’m quite stuck and I can’t migrate my project and not uploading new versions of my server.
Tnx for the help!

**Comment by cojalvo** [comment]
@stickfigure Any help will be appreciated.

**Comment by stickfigure** [comment]
Yes, that LatLng class is the right one. Objectify should persist and recover that just fine. However, you're getting a serialization exception from Jackson, which means you're trying to do some sort of JSON processing. That's not something that Objectify does, so it must be driven by your code.

If you post a full stacktrace, I can probably give you some suggestion for where in your code to look. But it probably won't be an Objectify problem, per-se.

**Comment by cojalvo** [comment]
Thanks for the response...
So the serialization error seems to come from the service endpoints infra, some of my request/response objects used the old GeoPt object and they were able to use it in the req/res and serialize or deserialize... and now they are unable to use the new LatLng that replacing the GeoPt... as It missing default constructor for the serializator... 
Any idea how can I solve this problem? or I must use other object for the req/res

**Comment by cojalvo** [comment]
So I wonder if I will extend `com.google.cloud.datastore.LatLng` and I will make the derived class to be serializable... will objectify be able to use this new class? so I can use it for both embedded entity and req/res object?

**Comment by stickfigure** [comment]
You have two options, a good one and a bad one:

1) The good one - figure out how to serialize LatLng with whatever infrastructure you're using. There's always a way. Looks like you're using Jackson, so making a Serializer or Deserializer is straightforward - you can even look in the `com.googlecode.objectify.util.jackson` package for some examples. The tricky bit is figuring out how to configure the ObjectMapper that your infrastructure uses. But you should be able to figure it out.

2) The bad one - write an Objectify `TranslatorFactory` that will convert between `GeoPt` (which your code uses) and `LatLng` which Google's low level library understands. This lets you kick the can down the road and leave your code more or less as-is... but it means you're forever dependent on the legacy GAE library that has `GeoPt`. If you want examples, look in the Objectify codebase for everything that extends `SimpleTranslatorFactory`. You'll want to extend `SimpleTranslatorFactory<GeoPt, LatLng>`.

**Comment by cojalvo** [comment]
Thanks! so now i see another error from objectify but now it `com.google.appengine.api.blobstore.BlobKey`
`com.googlecode.objectify.LoadException: Error loading Key{projectId=brilliant-will-93906, namespace=, path=[PathElement{kind=Track, id=4619005467295744, name=null}]}: Expected type ENTITY at path 'backgroundBlobKey' but instead found STRING`

Whats is the alternative class for the `com.google.appengine.api.blobstore.BlobKey` 
?

**Comment by stickfigure** [comment]
Looks like it's just a String. Must have been a part of the old Google SDK that wasn't brought forward to the new SDK. Which makes sense, since the legacy blobstore was abandoned in favor of GCS.
